// vuejs/src/components/Controls.vue
<template>
  <div>
    <tr v-for="c in controls" :key="c.name">
      <td class="key">{{ c.name }}</td>
      <td class="value" v-if="c.menu">
        <select v-model.number="c.value" v-on:change="updateValue(c.id,c.value)">
          <option v-for="m in c.menu" :key="m.label" :value="m.value">{{ m.label }}</option>
        </select>
      </td>        
      <td class="value" v-if="!c.menu && c.minimum == 0 && c.maximum == 1">
        <input
          v-model.number="c.value" true-value="1" false-value="0"
          type="checkbox" 
          v-on:change="updateValue(c.id,c.value)"
        />
      </td>        
      <td class="value" v-if="!c.menu && !(c.minimum == 0 && c.maximum == 1)">
        <v-slider
          v-model.number="c.value" 
          color="blue"
          thumb-label="true"          
          :min="c.minimum"
          :max="c.maximum" 
          v-on:change="updateValue(c.id,c.value)"
        >
          <template v-slot:prepend>{{c.minimum}}</template>
          <template v-slot:append>{{c.maximum}}
                <v-text-field
                  v-model.number="c.value"
                  v-on:change="updateValue(c.id,c.value)"
                ></v-text-field>
          </template>
        </v-slider>
      </td>
    </tr>
  </div>
</template>

<script>
import axios from "axios";

var serviceurl = "";

export default {
  mounted() {
    axios.get(serviceurl + "/api/controls").then(
      (response) => this.controls = response.data
    );
  },
  data() {
    return {
      controls: [],
    };
  },
  methods: {
    updateValue: function(id, value) {
      axios.post(serviceurl + "/api/control", {id, value} ).then(
        (response) => this.controls.filter((d) => d.id == id)[0].value = response.data.value
      );
    }
  }
};
</script>

<style scoped>
tr {
  width: 100%;
}
.key {
  width: 20%;
}
.value {
  width: 80%;
}
</style>

// angular/src/app/controls/controls.component.ts
import { Component, OnInit, Inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { DOCUMENT } from '@angular/common';

@Component({
  selector: 'app-controls',
  template: `
   <div>
	<table>
		<thead>
			<tr>
				<th>Name</th>
				<th>Current</th>
				<th>Min</th>
				<th>Max</th>
				<th>Value</th>
			</tr>
		</thead>
		<tbody>
			<tr *ngFor="let control of controlList; let index = index" >
				<td>{{control.name}}</td>
				<td>
					<input #name placeholder="{{control.value}}" type="text" size="8"/>				
				</td>
				<td>{{control.minimum}}</td>
				<td>
					<!-- combo for enumerate -->
					<select *ngIf="control.menu" 
							[value]="control.value" (change)="changed(control.id,$event.target.value,index)" 
							style="width: 300px">
								<option *ngFor="let menu of control.menu" [value]="menu.value">{{ menu.label }}</option>
					</select>
					<!-- checkbox for [0,1] -->
					<input *ngIf="!control.menu && ( (control.minimum==0) && (control.maximum==1) )"
							[checked]="control.value" (change)="changed(control.id,$event.target.checked?1:0,index)"
							type="checkbox" />							
					<!-- slider for others -->
					<input *ngIf="!control.menu && !( (control.minimum==0) && (control.maximum==1) )"
							[value]="control.value" (change)="changed(control.id,$event.target.value,index)"
							ng-trim="false" 
							min="{{control.minimum}}"
							max="{{control.maximum}}"
							type="range" 
							step="{{control.step}}"
							style="width: 300px; margin: 0px"/>							
				</td>
				<td>{{control.maximum}}</td>
			</tr>      
		</tbody>
	</table>
</div>
  `,
  styles: []
})

export class ControlsComponent implements OnInit {

	controlList = {};
	constructor(@Inject(DOCUMENT) private _document: any, 
				private _httpClient: HttpClient) {
	}
	
	ngOnInit() {
		this._httpClient.get(this._document.location.href + "/api/controls")
		    .subscribe(data => {
			     this.controlList = data;
		    });
	}	

	changed(id: string, value: any, idx: number) {
		value = parseInt(value)
		this._httpClient.post(this._document.location.href + "/api/control", {id, value}).subscribe( (data: any) => {
			    this.controlList[idx].value = data.value;		
		})
	}
}
