// angular/src/app/video/video.component.ts
import { Component, OnInit, Inject } from '@angular/core';
import { WebsocketService } from "../websocket.service";
import { DOCUMENT } from '@angular/common';

@Component({
  selector: 'app-video',
  template: `
    <img [src]="image" >
  `,
  styles: []
})
export class VideoComponent implements OnInit {
   image = "";
	
  constructor(@Inject(DOCUMENT) private _document: any,
  				private wsService: WebsocketService) { 
  }

  ngOnInit() {
	const wsurl = this._document.location.href.replace("http","ws") + "/ws";  
	let ws = this.wsService.connect(wsurl);
	ws.subscribe((response: MessageEvent) => {
		let data = response.data;
		if (data instanceof Blob) {
			new Response(data).arrayBuffer().then( (binary) => {
				var bytes = new Uint8Array(binary);	
				var binaryStr = "";
				for(let i=0;i<bytes.length;i++) binaryStr += String.fromCharCode(bytes[i]);
				this.image = 'data:image/jpeg;base64,' + btoa(binaryStr);
			})
		}
	});
  }

}

// vuejs/src/components/Video.vue
<template>
  <div>
    <div style="display: block">
      <button v-on:click="start">Start</button>
      <button v-on:click="stop">Stop</button>
    </div>
    <div style="display: block">
      <img v-if="visibility" :src="image" style="overflow: auto" />
    </div>
  </div>
</template>

<script>
import axios from "axios";

var serviceurl = "";

export default {
  data: function () {
    return {
      image: "",
      visibility: true,
    };
  },
  created: function () {
    console.log("Starting connection to WebSocket Server");
    const wsurl = document.location.href.replace("http", "ws") + "/ws";
    const connection = new WebSocket(wsurl);

    connection.onmessage = (message) => {
      let data = message.data;
      if (data instanceof Blob) {
        new Response(data).arrayBuffer().then((binary) => {
          var bytes = new Uint8Array(binary);
          var binaryStr = "";
          for (let i = 0; i < bytes.length; i++)
            binaryStr += String.fromCharCode(bytes[i]);
          this.image = "data:image/jpeg;base64," + btoa(binaryStr);
        });
      }
    };

    connection.onopen = function (event) {
      console.log("Successfully connected to websocket ...");
    };
  },
  methods: {
    start: function() {
      axios.get(serviceurl + "/api/start");
      this.visibility = true;
    },
    stop: function() {
      axios.get(serviceurl + "/api/stop");
      this.visibility = false;
    }
  }
};
</script>
